### ISSUE TITLE
how to set not scroll header layout and set scroll only content layout

### ISSUE THREAD

**Issue by rmvivek** [Reline/Google-Maps-BottomSheet#11]
how set header layout set toolbar bar not scroll but content layout only scroll line uber app bottom sheet animation.

**Comment by reline** [comment]
Optimally, when opening the bottom sheet to full screen the header would
actually turn into an action bar just like in the (previous) Google Maps
app, which cannot be scrolled. Does this fit into what you're looking for?

**Comment by rmvivek** [comment]
how to set Header layout act as a toolbar?

**Comment by rmvivek** [comment]
how to set content layout act as a buttom sheet?

**Comment by reline** [comment]
@rmvivek Please don't duplicate issues.
