### ISSUE TITLE
Cant add viewpager

### ISSUE THREAD

**Issue by rahulmmohan** [Reline/Google-Maps-BottomSheet#8]
Cant add viewpager as a behavior_content_layout. Viewpager not inflating

**Comment by Reline** [comment]
ViewPagers can't be added to the `android.support.design.widget.BottomSheetBehavior` either, so I'm considering this out of scope for this library. If you'd like, you can fork and contribute the solution yourself. Thanks.

**Comment by rahulmmohan** [comment]
Ok. What you think about why the ViewPager not supporting

**Comment by Reline** [comment]
This [library](https://github.com/laenger/ViewPagerBottomSheet) seems to have completed the job. 

Adding this into `View findScrollingChild(View view)` should do the trick:
```
       if (view instanceof ViewPager) {
            ViewPager viewPager = (ViewPager) view;
            final int currentItem = viewPager.getCurrentItem();
            for (int i = 0; i < viewPager.getChildCount(); i++) {
                final View child = viewPager.getChildAt(i);
                final ViewPager.LayoutParams layoutParams = (ViewPager.LayoutParams) child.getLayoutParams();
                if (!layoutParams.isDecor && currentItem == layoutParams.position) {
                    View scrollingChild = findScrollingChild(child);
                    if (scrollingChild != null) {
                        return scrollingChild;
                    }
                }
            }
        }
```
but `ViewPager.LayoutParams.position` is package-private, so you'll need to make a utils class like he's done [here](https://github.com/laenger/ViewPagerBottomSheet/blob/master/vpbs/src/main/java/android/support/v4/view/ViewPagerUtils.java).

**Comment by bafsheh** [comment]
hi you can solve problem like this 

` <android.support.v4.widget.NestedScrollView
        android:id="@+id/bottomsheet"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="bottom"
        android:background="@android:color/white"
        android:fillViewport="true"
        app:layout_behavior="com.github.reline.GoogleMapsBottomSheetBehavior">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">


            <android.support.v4.view.ViewPager xmlns:android="http://schemas.android.com/apk/res/android"
                android:id="@+id/header"
                android:layout_width="match_parent"
                android:layout_height="100dp"
                android:adjustViewBounds="true"
                android:background="@color/colorAccent"
                android:visibility="gone"/>

            <android.support.v7.widget.RecyclerView
                android:id="@+id/recycler_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical"
                android:scrollbars="none"
                />
        </LinearLayout>
    </android.support.v4.widget.NestedScrollView>`
